### PR TITLE
Completely overhaul the website.

### PR DESCRIPTION
**Pull request by kgriffs**

### CODE REVIEW

**Comment by kgriffs** [comment]
Do you mean from the bootstrap theme dir? TBH I just left most of it intact for future use/reference.

**Comment by jmvrbanac** [comment]
Ahh ok. Well, it looks good to me. Do you want me to go ahead and merge this or are you still working on it?

**Comment by kgriffs** [comment]
I think it's good to go at this point if you'd like to pull the trigger. Thanks!

**Comment by kgriffs** [comment]
Oops, found one last thing I forgot to do. Now we're ready to rock. :)

**Pull request merged**
